int( )
int ( ) Function is Used To Convert the String into Integer ...
          name = input("What's your name ? ")
          age =int(  input("How old are you? "))
          print("hello",name,  "you are",age, "Years old")
          print("but you will be", age + 2,"years old two years later")
          How old are you? oxf
          ValueError: invalid literal for int() with base 10: 'oxf'


       1.  print(int('ox64'))
       ----> 1  print(int('ox64'))
       ValueError: invalid literal for int() with base 10: 'ox64'
        2.  print(int('0b1100100'))
       ----> 2  print(int('0b1100100'))
       ValueError: invalid literal for int() with base 10: ' 0b1100100 '