Float into Hexadecimal value
x = float(hexrep)
    The hex() method converts a float to a hexadecimal string 
    representation using Python's internal format. 
    For example, 
    0.125  might be represented as 0x1.0000000000000p-3.

    The float() function in Python expects a string representation of 
    a decimal (base-10) number that it can parse into a float.  
    It does not directly interpret or convert from a hexadecimal 
    representation like 0x1.0000000000000p-3.

If Try then we will get error:
Output:
            x = 0.125
            x in hex = 0x1.0000000000000p-3
            Type of hexrep =  <class 'str'>
  ---->  x = float(hexrep)
            print("x =",x)-->(This will not get executed )

ValueError: could not convert string to float: '0x1.0000000000000p-3'